spring:
  profiles:
    active: data, price, en



#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR

#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#logging.pattern.file= "%d{yyyy-MM-dd } [%thread] %-5level %logger{36} - %msg%n"


